skip_tags: false
skip_non_tags: true
build:
  verbosity: minimal

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build:win
  - 7z a elecron-win32-x64.zip %APPVEYOR_BUILD_FOLDER%\release\elecron-win32-x64

test: off

artifacts:
  - path: ${APPVEYOR_BUILD_FOLDER}\release\elecron-win32-x64.zip
    name: zipped

deploy:
  provider: GitHub
  description: 'Release description'
  tag: ${APPVEYOR_REPO_TAG_NAME}
  artifact: zipped
  on:
      branch: master
  auth_token:
    secure: MHFFc5H6WcQ9vaR6Gm6SY9SBqHyqi5shHqK4xXk7VpqpZx9fxM9V4HYSY+TWuJeS
